Milestone4
nyatindopatrick/calculator pull request #4
Opened 2021-03-03 12:12 UTC by nyatindopatrick

Add logic folder, calculate and operate methods.

2021-03-03 12:41 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @nyatindopatrick :hand: 
Great job on this milestone so far :clap: :+1: 
But we need to make some changes before moving on.

- [ ] Right now most of your README file is the text generated by `create-react-app`. We need to add a more descriptive text to improve your README file and, therefore, make your repository more professional. It's best practice to add information about how to use your application (instructions on how to set up and which script to use to run your app). You can use this template [here](https://github.com/microverseinc/readme-template), create by Microverse to help to build professional README files. 
![Screenshot from 2021-03-03 09-28-06](https://user-images.githubusercontent.com/30977845/109805916-c877b800-7c02-11eb-8b12-f27e7d5e044d.png)

- [ ] Check my comments below.

Happy coding :computer: 
**Sérgio Torres**

2021-03-03 12:41 UTC, Torres-ssf commented on src/logic/calculate.js
> +// eslint-disable-next-line consistent-return
- [ ] We should avoid disabling Eslint rules.  Instead, we need to make our code adequate with the specific rule. We can learn more about this specific rule [here](https://eslint.org/docs/rules/consistent-return)

2021-03-03 12:41 UTC, Torres-ssf commented on src/logic/calculate.js
> +  }
- [ ] We need to improve the calculate function. Here we need to deal with any possible button that it's pressed within the calculator. Like: `AC`, `.`, `=`, and any digits.

- [ ] Here we also need to deal with the operation. Meaning that, if it is time to do an operation, we need to call the operation function to deal with it.

2021-03-03 12:41 UTC, Torres-ssf commented on src/logic/operate.js
> +  // eslint-disable-next-line default-case
- [ ] We need to address the Eslint error here. Check this [link](https://eslint.org/docs/rules/default-case)

2021-03-04 07:03 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-03-04 07:03 UTC, merged